defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"
exclude: [
  '.gitignore',
  'CNAME',
  'LICENSE',
  'README.md',
  'sketch',
]
kramdown:
  input: GFM
  syntax_highlighter: rouge
markdown: kramdown
permalink: pretty
sass:
  style: compressed
  sass_dir: 'assets/styles'
timezone: America/New_York

title: Tom Meagher
description: "I'm Tom Meagher (MAH-hur): a programmer, blogger, and walk enthusiast."
url: "https://meagher.co"
author: "Tom Meagher"
keywords: 'tom, tomfme, meagher, code, design, startups, technology, tech, design'
